// <auto-generated />
using System;
using FatihBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FatihBank.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220803103501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FatihBank.Models.MSS_ACC_Checks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.ToTable("MSS_ACC_Checks");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Daily_Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("additional_minutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("Date");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("in_come_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("is_absent")
                        .HasColumnType("int");

                    b.Property<int>("is_excused")
                        .HasColumnType("int");

                    b.Property<int>("late_minutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("leave_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("scheduleId")
                        .HasColumnType("int");

                    b.Property<int>("schedule_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.HasIndex("scheduleId");

                    b.ToTable("MSS_ATT_Daily_Attendance");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Discounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("Date");

                    b.Property<double>("discount")
                        .HasColumnType("float");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("on_salary")
                        .HasColumnType("bit");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.ToTable("MSS_ATT_Discounts");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Excuses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("actual_return_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("excusesTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("excuses_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("excuses_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("leave_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("process_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("processed_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("request_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("return_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.HasIndex("excusesTypeId");

                    b.ToTable("MSS_ATT_Excuses");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_ExcusesTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_ATT_ExcusesTypes");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Month_Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("absent_days")
                        .HasColumnType("float");

                    b.Property<double?>("add_hours")
                        .HasColumnType("float");

                    b.Property<double>("due_days")
                        .HasColumnType("float");

                    b.Property<double>("due_hours")
                        .HasColumnType("float");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<double>("excused_days")
                        .HasColumnType("float");

                    b.Property<double>("late_hours")
                        .HasColumnType("float");

                    b.Property<string>("month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("real_days")
                        .HasColumnType("float");

                    b.Property<double>("real_hours")
                        .HasColumnType("float");

                    b.Property<int?>("scheduleId")
                        .HasColumnType("int");

                    b.Property<int>("schedule_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.HasIndex("scheduleId");

                    b.ToTable("MSS_ATT_Month_Info");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Month_Salaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("added_amount")
                        .HasColumnType("float");

                    b.Property<int>("attended_days")
                        .HasColumnType("int");

                    b.Property<double>("basic_salary")
                        .HasColumnType("float");

                    b.Property<double>("discount_amount")
                        .HasColumnType("float");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_paid")
                        .HasColumnType("bit");

                    b.Property<string>("month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("net_salary")
                        .HasColumnType("float");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.ToTable("MSS_ATT_Month_Salaries");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Rewards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("Date");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("on_salary")
                        .HasColumnType("bit");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("reward")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.ToTable("MSS_ATT_Rewards");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Vacations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("no_of_days")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("process_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("processed_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("request_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int?>("vacationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("vacation_type")
                        .HasColumnType("int");

                    b.Property<int>("vacationsTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.HasIndex("vacationsTypeId");

                    b.ToTable("MSS_ATT_Vacations");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_VacationsTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_ATT_VacationsTypes");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_AVG_MainAvg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("currency1Id")
                        .HasColumnType("int");

                    b.Property<double>("currency1_amount")
                        .HasColumnType("float");

                    b.Property<int?>("currency2Id")
                        .HasColumnType("int");

                    b.Property<double>("currency2_amount")
                        .HasColumnType("float");

                    b.Property<int>("currency_1")
                        .HasColumnType("int");

                    b.Property<int>("currency_2")
                        .HasColumnType("int");

                    b.Property<int?>("exchange_account")
                        .HasColumnType("int");

                    b.Property<int?>("exchange_accountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("currency1Id");

                    b.HasIndex("currency2Id");

                    b.HasIndex("exchange_accountId");

                    b.ToTable("MSS_AVG_MainAvg");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CAS_Operations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int>("cashier_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cashierId");

                    b.ToTable("MSS_CAS_Operations");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CHT_ChatList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("s_1")
                        .HasColumnType("int");

                    b.Property<int>("s_2")
                        .HasColumnType("int");

                    b.Property<int?>("user1Id")
                        .HasColumnType("int");

                    b.Property<int?>("user2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user1Id");

                    b.HasIndex("user2Id");

                    b.ToTable("MSS_CHT_ChatList");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CUS_Add_To_Monthly_List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<double>("percent")
                        .HasColumnType("float");

                    b.Property<int?>("profitAccountId")
                        .HasColumnType("int");

                    b.Property<int>("profit_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("currencyId");

                    b.HasIndex("profitAccountId");

                    b.ToTable("MSS_CUS_Add_To_Monthly_List");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("commissioned")
                        .HasColumnType("int");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<int>("current_amount")
                        .HasColumnType("int");

                    b.Property<int?>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("oldId")
                        .HasColumnType("int");

                    b.Property<int?>("profit_id")
                        .HasColumnType("int");

                    b.Property<double>("start_amount")
                        .HasColumnType("float");

                    b.Property<int?>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("currencyId");

                    b.HasIndex("customerId");

                    b.ToTable("MSS_DEF_Accounts");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_AVGs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("amount1")
                        .HasColumnType("float");

                    b.Property<double>("amount2")
                        .HasColumnType("float");

                    b.Property<double>("avg")
                        .HasColumnType("float");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("currencyId");

                    b.ToTable("MSS_DEF_AVGs");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Cashiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("currencyId");

                    b.ToTable("MSS_DEF_Cashiers");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("profitAccountId")
                        .HasColumnType("int");

                    b.Property<int>("profit_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("total_amount")
                        .HasColumnType("float");

                    b.Property<double?>("total_percent")
                        .HasColumnType("float");

                    b.Property<double>("total_profit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("profitAccountId");

                    b.ToTable("MSS_DEF_Commission");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Countries");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Currencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entery_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("isMain")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortcut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Currencies");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("canOverLimit")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employee")
                        .HasColumnType("int");

                    b.Property<int?>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("entery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("isPublic")
                        .HasColumnType("int");

                    b.Property<int?>("is_private")
                        .HasColumnType("int");

                    b.Property<double?>("limit")
                        .HasColumnType("float");

                    b.Property<long?>("mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("notificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personal_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("phone")
                        .HasColumnType("bigint");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shipping")
                        .HasColumnType("int");

                    b.Property<int>("sms")
                        .HasColumnType("int");

                    b.Property<int?>("special")
                        .HasColumnType("int");

                    b.Property<int>("suspended")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Customers");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("idphoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("phone")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Employees");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Exchange_Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("currency2Id")
                        .HasColumnType("int");

                    b.Property<int?>("currency2_id")
                        .HasColumnType("int");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double>("start_amount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("currency2Id");

                    b.HasIndex("currencyId");

                    b.HasIndex("parentId");

                    b.ToTable("MSS_DEF_Exchange_Accounts");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Groups");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Journals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("total_amount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Journals");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_MCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("account1Id")
                        .HasColumnType("int");

                    b.Property<int>("account1_id")
                        .HasColumnType("int");

                    b.Property<int?>("account2Id")
                        .HasColumnType("int");

                    b.Property<int>("account2_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<double?>("commission")
                        .HasColumnType("float");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes_for_profit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("profitAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("profit_id")
                        .HasColumnType("int");

                    b.Property<int?>("type")
                        .HasColumnType("int");

                    b.Property<int?>("type_of_operation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("account1Id");

                    b.HasIndex("account2Id");

                    b.HasIndex("profitAccountId");

                    b.ToTable("MSS_DEF_MCD");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Modules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("group")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Modules");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("storeId")
                        .HasColumnType("int");

                    b.Property<int>("store_id")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("storeId");

                    b.ToTable("MSS_DEF_Orders");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_P_Prices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<int>("divide")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("currencyId");

                    b.HasIndex("userId");

                    b.ToTable("MSS_DEF_P_Prices");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("module1Id")
                        .HasColumnType("int");

                    b.Property<int>("module_id")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("module1Id");

                    b.HasIndex("userId");

                    b.ToTable("MSS_DEF_Permissions");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Prices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("b_price")
                        .HasColumnType("float");

                    b.Property<double>("commission")
                        .HasColumnType("float");

                    b.Property<int?>("currency1Id")
                        .HasColumnType("int");

                    b.Property<int>("currency1_id")
                        .HasColumnType("int");

                    b.Property<int?>("currency2Id")
                        .HasColumnType("int");

                    b.Property<int>("currency2_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<double>("s_price")
                        .HasColumnType("float");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("currency1Id");

                    b.HasIndex("currency2Id");

                    b.ToTable("MSS_DEF_Prices");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("amount_of_accepted_late")
                        .HasColumnType("int");

                    b.Property<int>("day_of_holiday")
                        .HasColumnType("int");

                    b.Property<double>("discount_for_late_pre_hour")
                        .HasColumnType("float");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("reward_for_additional_work_per_hour")
                        .HasColumnType("float");

                    b.Property<DateTime>("work_leave_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("work_start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Schedule");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_SMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<long>("phone_number")
                        .HasColumnType("bigint");

                    b.Property<int>("sent_by")
                        .HasColumnType("int");

                    b.Property<int?>("sent_by_userId")
                        .HasColumnType("int");

                    b.Property<int?>("sent_to_CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("sent_to_customer")
                        .HasColumnType("int");

                    b.Property<string>("sms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("sent_by_userId");

                    b.HasIndex("sent_to_CustomerId");

                    b.ToTable("MSS_DEF_SMS");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Stores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<int>("country_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.ToTable("MSS_DEF_Stores");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int>("cashier_id")
                        .HasColumnType("int");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<int>("country_id")
                        .HasColumnType("int");

                    b.Property<int?>("currency2Id")
                        .HasColumnType("int");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("currency_2")
                        .HasColumnType("int");

                    b.Property<int>("currency_id")
                        .HasColumnType("int");

                    b.Property<double>("current_total")
                        .HasColumnType("float");

                    b.Property<double>("current_total2")
                        .HasColumnType("float");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("exchangeId")
                        .HasColumnType("int");

                    b.Property<int>("exchange_account")
                        .HasColumnType("int");

                    b.Property<double?>("exchange_account1")
                        .HasColumnType("float");

                    b.Property<double?>("exchange_account2")
                        .HasColumnType("float");

                    b.Property<double?>("extra_price")
                        .HasColumnType("float");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int?>("sub_id")
                        .HasColumnType("int");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("cashierId");

                    b.HasIndex("countryId");

                    b.HasIndex("currency2Id");

                    b.HasIndex("currencyId");

                    b.HasIndex("exchangeId");

                    b.ToTable("MSS_DEF_Transactions");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<int?>("is_online")
                        .HasColumnType("int");

                    b.Property<string>("loginName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_DEF_Users");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Vouchers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Currency1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Currency2Id")
                        .HasColumnType("int");

                    b.Property<int?>("account2Id")
                        .HasColumnType("int");

                    b.Property<int?>("account2_id")
                        .HasColumnType("int");

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int>("cashier_id")
                        .HasColumnType("int");

                    b.Property<int?>("currency1")
                        .HasColumnType("int");

                    b.Property<int?>("currency2")
                        .HasColumnType("int");

                    b.Property<double>("current_total")
                        .HasColumnType("float");

                    b.Property<double>("current_total2")
                        .HasColumnType("float");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("num")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double?>("total")
                        .HasColumnType("float");

                    b.Property<double?>("total_cashier")
                        .HasColumnType("float");

                    b.Property<int?>("transactionId")
                        .HasColumnType("int");

                    b.Property<int?>("transaction_id")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<int?>("type2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Currency1Id");

                    b.HasIndex("Currency2Id");

                    b.HasIndex("account2Id");

                    b.HasIndex("accountId");

                    b.HasIndex("cashierId");

                    b.HasIndex("transactionId");

                    b.ToTable("MSS_DEF_Vouchers");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_FAV_FavAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.ToTable("MSS_FAV_FavAccounts");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_FIN_Avg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("currency1_amount")
                        .HasColumnType("float");

                    b.Property<double>("currency2_amount")
                        .HasColumnType("float");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("mainAvgId")
                        .HasColumnType("int");

                    b.Property<int>("main_avg")
                        .HasColumnType("int");

                    b.Property<int>("operation_id")
                        .HasColumnType("int");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("mainAvgId");

                    b.HasIndex("parentId");

                    b.ToTable("MSS_FIN_Avg");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_INF_Action_Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MSS_INF_Action_Types");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_INF_Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("action_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("fromId")
                        .HasColumnType("int");

                    b.Property<int>("from_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("obj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int?>("toId")
                        .HasColumnType("int");

                    b.Property<int>("to_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fromId");

                    b.HasIndex("toId");

                    b.ToTable("MSS_INF_Notifications");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_INF_RegisterationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Action_typeId")
                        .HasColumnType("int");

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int?>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("action_type")
                        .HasColumnType("int");

                    b.Property<double?>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int?>("cashier_id")
                        .HasColumnType("int");

                    b.Property<string>("computer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int?>("currency_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("exchangeId")
                        .HasColumnType("int");

                    b.Property<int?>("exchange_id")
                        .HasColumnType("int");

                    b.Property<int>("operation_id")
                        .HasColumnType("int");

                    b.Property<int>("operation_type")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<int?>("subtype")
                        .HasColumnType("int");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action_typeId");

                    b.HasIndex("accountId");

                    b.HasIndex("cashierId");

                    b.HasIndex("currencyId");

                    b.HasIndex("exchangeId");

                    b.HasIndex("userId");

                    b.ToTable("MSS_INF_RegisterationFile");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_JOU_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<double?>("currencyAmount")
                        .HasColumnType("float");

                    b.Property<int?>("currencyId")
                        .HasColumnType("int");

                    b.Property<int?>("customerId")
                        .HasColumnType("int");

                    b.Property<double?>("inAmount")
                        .HasColumnType("float");

                    b.Property<int?>("journalId")
                        .HasColumnType("int");

                    b.Property<double?>("outAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("currencyId");

                    b.HasIndex("customerId");

                    b.HasIndex("journalId");

                    b.ToTable("MSS_JOU_Details");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_N_DEF_Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("attendance_schedule")
                        .HasColumnType("int");

                    b.Property<string>("birth_place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("customerId")
                        .HasColumnType("int");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enroll_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("entered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("father_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finger_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("identity_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("is_resigned")
                        .HasColumnType("int");

                    b.Property<string>("job_position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("mobile_number")
                        .HasColumnType("bigint");

                    b.Property<string>("mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("national_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personal_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phone_number")
                        .HasColumnType("bigint");

                    b.Property<int?>("salary_account")
                        .HasColumnType("int");

                    b.Property<double>("salary_per_hour")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("customerId");

                    b.ToTable("MSS_N_DEF_Employees");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_TRS_Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int>("cashier_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deliever_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliever_from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("delievered_by")
                        .HasColumnType("int");

                    b.Property<int>("is_delievered")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("cashierId");

                    b.ToTable("MSS_TRS_Companies");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_TRS_Individuals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int?>("cashierId")
                        .HasColumnType("int");

                    b.Property<int>("cashier_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deliever_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliever_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("delievered_by")
                        .HasColumnType("int");

                    b.Property<int>("is_delievered")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("accountId");

                    b.HasIndex("cashierId");

                    b.ToTable("MSS_TRS_Individuals");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ACC_Checks", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany("checks")
                        .HasForeignKey("accountId");

                    b.Navigation("account");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Daily_Attendance", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Schedule", "schedule")
                        .WithMany()
                        .HasForeignKey("scheduleId");

                    b.Navigation("employee");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Discounts", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Excuses", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.HasOne("FatihBank.Models.MSS_ATT_ExcusesTypes", "excusesType")
                        .WithMany()
                        .HasForeignKey("excusesTypeId");

                    b.Navigation("employee");

                    b.Navigation("excusesType");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Month_Info", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Schedule", "schedule")
                        .WithMany("month_Infos")
                        .HasForeignKey("scheduleId");

                    b.Navigation("employee");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Month_Salaries", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Rewards", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_Vacations", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Employees", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId");

                    b.HasOne("FatihBank.Models.MSS_ATT_VacationsTypes", "vacationsType")
                        .WithMany("vacations")
                        .HasForeignKey("vacationsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("vacationsType");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_AVG_MainAvg", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency1")
                        .WithMany()
                        .HasForeignKey("currency1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency2")
                        .WithMany()
                        .HasForeignKey("currency2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Exchange_Accounts", "exchange_Account")
                        .WithMany()
                        .HasForeignKey("exchange_accountId");

                    b.Navigation("currency1");

                    b.Navigation("currency2");

                    b.Navigation("exchange_Account");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CAS_Operations", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany("operations")
                        .HasForeignKey("cashierId");

                    b.Navigation("cashier");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CHT_ChatList", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "user1")
                        .WithMany()
                        .HasForeignKey("user1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "user2")
                        .WithMany()
                        .HasForeignKey("user2Id");

                    b.Navigation("user1");

                    b.Navigation("user2");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_CUS_Add_To_Monthly_List", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "profitAccount")
                        .WithMany()
                        .HasForeignKey("profitAccountId");

                    b.Navigation("account");

                    b.Navigation("currency");

                    b.Navigation("profitAccount");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Accounts", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Customers", "customer")
                        .WithMany("accounts")
                        .HasForeignKey("customerId");

                    b.Navigation("currency");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_AVGs", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.Navigation("currency");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Cashiers", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.Navigation("currency");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Commission", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "profitAccount")
                        .WithMany()
                        .HasForeignKey("profitAccountId");

                    b.Navigation("account");

                    b.Navigation("profitAccount");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Exchange_Accounts", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency2")
                        .WithMany()
                        .HasForeignKey("currency2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Exchange_Accounts", "parent")
                        .WithMany()
                        .HasForeignKey("parentId");

                    b.Navigation("currency");

                    b.Navigation("currency2");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_MCD", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account1")
                        .WithMany()
                        .HasForeignKey("account1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account2")
                        .WithMany()
                        .HasForeignKey("account2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "profitAccount")
                        .WithMany()
                        .HasForeignKey("profitAccountId");

                    b.Navigation("account1");

                    b.Navigation("account2");

                    b.Navigation("profitAccount");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Orders", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Stores", "store")
                        .WithMany()
                        .HasForeignKey("storeId");

                    b.Navigation("account");

                    b.Navigation("store");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_P_Prices", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("currency");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Permissions", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Modules", "module1")
                        .WithMany("permissions")
                        .HasForeignKey("module1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "user")
                        .WithMany("permissions")
                        .HasForeignKey("userId");

                    b.Navigation("module1");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Prices", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency1")
                        .WithMany()
                        .HasForeignKey("currency1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency2")
                        .WithMany()
                        .HasForeignKey("currency2Id");

                    b.Navigation("currency1");

                    b.Navigation("currency2");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_SMS", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "sent_by_user")
                        .WithMany()
                        .HasForeignKey("sent_by_userId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Customers", "sent_to_Customer")
                        .WithMany()
                        .HasForeignKey("sent_to_CustomerId");

                    b.Navigation("sent_by_user");

                    b.Navigation("sent_to_Customer");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Stores", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Countries", "country")
                        .WithMany("stores")
                        .HasForeignKey("countryId");

                    b.Navigation("country");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Transactions", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany()
                        .HasForeignKey("cashierId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Countries", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency2")
                        .WithMany()
                        .HasForeignKey("currency2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Exchange_Accounts", "exchange")
                        .WithMany()
                        .HasForeignKey("exchangeId");

                    b.Navigation("account");

                    b.Navigation("cashier");

                    b.Navigation("country");

                    b.Navigation("currency");

                    b.Navigation("currency2");

                    b.Navigation("exchange");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Vouchers", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "Currency1")
                        .WithMany()
                        .HasForeignKey("Currency1Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "Currency2")
                        .WithMany()
                        .HasForeignKey("Currency2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account2")
                        .WithMany()
                        .HasForeignKey("account2Id");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany()
                        .HasForeignKey("cashierId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Transactions", "transaction")
                        .WithMany()
                        .HasForeignKey("transactionId");

                    b.Navigation("Currency1");

                    b.Navigation("Currency2");

                    b.Navigation("account");

                    b.Navigation("account2");

                    b.Navigation("cashier");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_FAV_FavAccounts", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.Navigation("account");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_FIN_Avg", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_AVG_MainAvg", "mainAvg")
                        .WithMany()
                        .HasForeignKey("mainAvgId");

                    b.HasOne("FatihBank.Models.MSS_FIN_Avg", "parent")
                        .WithMany()
                        .HasForeignKey("parentId");

                    b.Navigation("mainAvg");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_INF_Notifications", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "from")
                        .WithMany()
                        .HasForeignKey("fromId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "to")
                        .WithMany()
                        .HasForeignKey("toId");

                    b.Navigation("from");

                    b.Navigation("to");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_INF_RegisterationFile", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_INF_Action_Types", "Action_Type")
                        .WithMany()
                        .HasForeignKey("Action_typeId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany()
                        .HasForeignKey("cashierId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Exchange_Accounts", "exchange")
                        .WithMany()
                        .HasForeignKey("exchangeId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Users", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("Action_Type");

                    b.Navigation("account");

                    b.Navigation("cashier");

                    b.Navigation("currency");

                    b.Navigation("exchange");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_JOU_Details", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Currencies", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Customers", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Journals", "journal")
                        .WithMany("details")
                        .HasForeignKey("journalId");

                    b.Navigation("account");

                    b.Navigation("currency");

                    b.Navigation("customer");

                    b.Navigation("journal");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_N_DEF_Employees", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Customers", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_TRS_Companies", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany()
                        .HasForeignKey("cashierId");

                    b.Navigation("account");

                    b.Navigation("cashier");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_TRS_Individuals", b =>
                {
                    b.HasOne("FatihBank.Models.MSS_DEF_Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("FatihBank.Models.MSS_DEF_Cashiers", "cashier")
                        .WithMany()
                        .HasForeignKey("cashierId");

                    b.Navigation("account");

                    b.Navigation("cashier");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_ATT_VacationsTypes", b =>
                {
                    b.Navigation("vacations");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Accounts", b =>
                {
                    b.Navigation("checks");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Cashiers", b =>
                {
                    b.Navigation("operations");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Countries", b =>
                {
                    b.Navigation("stores");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Customers", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Journals", b =>
                {
                    b.Navigation("details");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Modules", b =>
                {
                    b.Navigation("permissions");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Schedule", b =>
                {
                    b.Navigation("month_Infos");
                });

            modelBuilder.Entity("FatihBank.Models.MSS_DEF_Users", b =>
                {
                    b.Navigation("permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
